wandb_version: 1

dataset:
  desc: null
  value: cifar10
grayscale:
  desc: null
  value: false
num_workers:
  desc: null
  value: 0
batch_size:
  desc: null
  value: 50
lr:
  desc: null
  value: 0.0025
weight_decay:
  desc: null
  value: 0.05
epochs:
  desc: null
  value: 200
n_layers:
  desc: null
  value: 2
d_model:
  desc: null
  value: 5
d_hidden:
  desc: null
  value: 5
dropout:
  desc: null
  value: 0.1
prenorm:
  desc: null
  value: true
norm:
  desc: null
  value: BN
cell:
  desc: null
  value: rnn
resume:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.8.13
    cli_version: 0.15.2
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1683727220.009535
    t:
      1:
      - 1
      - 41
      - 49
      - 50
      - 55
      - 63
      2:
      - 1
      - 41
      - 49
      - 50
      - 55
      - 63
      3:
      - 2
      - 3
      - 5
      - 13
      - 14
      - 16
      - 23
      4: 3.8.13
      5: 0.15.2
      8:
      - 1
      - 5
